from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, List, Dict, Any, Tuple

import numpy as np
import torch

from config import ExpCfg, CFG
from env import CollectDataEnv
from condition import ConditionBuilder, ConditionBatch
from diffusion_nets import DiffusionPolicy
from replay_diffusion import ReplayBufferDiffusion


# ============================================================
# Rollout records
# ============================================================
@dataclass
class ChunkPlan:
    """
    One planned chunk generated by the diffusion policy.

    Shapes
    ------
    action_chunk_env:
        (H, act_dim)

    action_chunk_unit:
        (H, act_dim), normalized in [-1, 1]
    """
    action_chunk_env: np.ndarray
    action_chunk_unit: Optional[np.ndarray]
    exec_len: int


@dataclass
class RunnerStepRecord:
    """
    One actually executed env step.
    """
    obs: np.ndarray
    act_flat: np.ndarray
    rew: float
    next_obs: np.ndarray
    done: bool
    info: Dict[str, Any]


@dataclass
class ChunkExecutionResult:
    """
    Result of executing one chunk partially or fully.

    Fields
    ------
    plan:
        the generated chunk plan

    steps:
        list of actually executed step records

    final_obs:
        observation after the last executed step

    total_reward:
        sum of rewards over executed steps
    """
    plan: ChunkPlan
    steps: List[RunnerStepRecord]
    final_obs: np.ndarray
    total_reward: float


# ============================================================
# History buffer
# ============================================================
class ObsHistoryBuffer:
    """
    Small in-memory buffer for recent observations.

    Used by runner to construct:
    - actor condition history
    - critic state history

    This buffer is episode-local and should be reset every episode.
    """

    def __init__(self, obs_dim: int, max_len: int):
        assert obs_dim > 0
        assert max_len >= 1
        self.obs_dim = int(obs_dim)
        self.max_len = int(max_len)
        self._buf: List[np.ndarray] = []

    def reset(self) -> None:
        self._buf = []

    def append(self, obs: np.ndarray) -> None:
        obs = np.asarray(obs, dtype=np.float32).reshape(-1)
        assert obs.shape[0] == self.obs_dim, (
            f"ObsHistoryBuffer dim mismatch: {obs.shape[0]} vs {self.obs_dim}"
        )
        self._buf.append(obs.copy())
        if len(self._buf) > self.max_len:
            self._buf = self._buf[-self.max_len:]

    def get(self) -> np.ndarray:
        """
        Return shape:
            (T, obs_dim)

        where 1 <= T <= max_len if buffer non-empty
        """
        if len(self._buf) == 0:
            raise RuntimeError("ObsHistoryBuffer is empty.")
        return np.stack(self._buf, axis=0).astype(np.float32)

    def get_padded(self, target_len: int) -> np.ndarray:
        """
        Return fixed-length history:
            (target_len, obs_dim)

        Left-pad by repeating earliest obs if needed.
        """
        assert target_len >= 1
        arr = self.get()  # (T,D)
        tlen = arr.shape[0]
        if tlen >= target_len:
            return arr[-target_len:].copy()

        pad_n = target_len - tlen
        pad = np.repeat(arr[:1], repeats=pad_n, axis=0)
        return np.concatenate([pad, arr], axis=0).astype(np.float32)

    def last(self) -> np.ndarray:
        if len(self._buf) == 0:
            raise RuntimeError("ObsHistoryBuffer is empty.")
        return self._buf[-1].copy()

    def __len__(self) -> int:
        return len(self._buf)


# ============================================================
# Main runner
# ============================================================
class DiffusionRunner:
    """
    Execution-layer runner between:
        diffusion policy <-> env

    Responsibilities
    ----------------
    1) Build actor condition from current obs/history
    2) Ask policy for one action chunk
    3) Execute only the first K actions (exec_len)
    4) Store step transitions into replay
    5) Maintain episode-local observation history

    Important
    ---------
    The env remains step-based.
    Chunk execution is entirely handled here.
    """

    def __init__(
        self,
        env: CollectDataEnv,
        policy: DiffusionPolicy,
        condition_builder: ConditionBuilder,
        replay: Optional[ReplayBufferDiffusion] = None,
        cfg: Optional[ExpCfg] = None,
        device: str = "cpu",
    ):
        self.cfg = cfg or CFG
        self.cfg.validate()

        self.env = env
        self.policy = policy
        self.cond_builder = condition_builder
        self.replay = replay
        self.device = torch.device(device)

        self.obs_dim = int(self.env.obs_dim())
        self.act_dim = int(self.env.act_dim())
        self.n_uavs = int(self.cfg.env.n_uavs)

        self.chunk_len = int(self.cfg.chunk.chunk_len)
        self.exec_len = int(self.cfg.chunk.exec_len)

        # episode-local history length should be enough for both actor and critic
        hist_len = max(
            int(self.cfg.adapter.actor_condition_horizon),
            int(self.cfg.critic.state_horizon),
            1,
        )
        self.obs_history = ObsHistoryBuffer(obs_dim=self.obs_dim, max_len=hist_len)

    # ============================================================
    # Episode management
    # ============================================================
    def reset_episode(self) -> np.ndarray:
        """
        Reset env and local runner history.

        Returns
        -------
        obs:
            initial observation
        """
        obs = self.env.reset().astype(np.float32)
        self.obs_history.reset()
        self.obs_history.append(obs)

        if self.replay is not None:
            self.replay.start_new_episode()

        return obs

    # ============================================================
    # Condition construction
    # ============================================================
    def build_actor_condition(self, obs: Optional[np.ndarray] = None) -> ConditionBatch:
        """
        Build current actor-side condition batch.

        Current first version:
        - batch size = 1 during interaction
        - use latest obs as current obs
        - pass obs history for future extensibility
        """
        if obs is None:
            obs = self.obs_history.last()

        actor_hist_len = int(self.cfg.adapter.actor_condition_horizon)
        critic_hist_len = int(self.cfg.critic.state_horizon)

        obs_hist = self.obs_history.get_padded(actor_hist_len)
        critic_hist = self.obs_history.get_padded(critic_hist_len)

        cond = self.cond_builder.build_condition(
            obs_batch=obs[None, :],                  # (1,D)
            obs_history=obs_hist[None, :, :],       # (1,Ha,D)
            critic_obs_history=critic_hist[None, :, :],  # (1,Hc,D)
        )
        return cond

    # ============================================================
    # Action plan generation
    # ============================================================
    @torch.no_grad()
    def plan_chunk(
        self,
        obs: Optional[np.ndarray] = None,
        deterministic: bool = False,
        return_unit: bool = True,
    ) -> ChunkPlan:
        """
        Generate one action chunk from current condition.

        Returns a chunk plan but does not execute it.
        """
        cond = self.build_actor_condition(obs=obs)

        if return_unit:
            a_env, a_unit = self.policy.sample_chunk_env(
                cond=cond,
                deterministic=deterministic,
                return_unit=True,
            )
            a_env_np = a_env.squeeze(0).detach().cpu().numpy().astype(np.float32)
            a_unit_np = a_unit.squeeze(0).detach().cpu().numpy().astype(np.float32)
        else:
            a_env = self.policy.sample_chunk_env(
                cond=cond,
                deterministic=deterministic,
                return_unit=False,
            )
            a_env_np = a_env.squeeze(0).detach().cpu().numpy().astype(np.float32)
            a_unit_np = None

        return ChunkPlan(
            action_chunk_env=a_env_np,
            action_chunk_unit=a_unit_np,
            exec_len=self.exec_len,
        )

    # ============================================================
    # Chunk execution
    # ============================================================
    def execute_chunk_plan(
        self,
        plan: ChunkPlan,
        store_replay: bool = True,
    ) -> ChunkExecutionResult:
        """
        Execute the first K actions of the provided chunk plan.

        Parameters
        ----------
        plan:
            generated chunk
        store_replay:
            whether to store executed steps into replay

        Returns
        -------
        ChunkExecutionResult
        """
        steps: List[RunnerStepRecord] = []
        total_reward = 0.0

        k = int(plan.exec_len)
        assert k >= 1
        assert plan.action_chunk_env.shape[0] >= k

        cur_obs = self.obs_history.last()

        for i in range(k):
            act_flat = plan.action_chunk_env[i].reshape(-1).astype(np.float32)
            act_env = self._flat_to_env_action(act_flat)

            next_obs, rew, done, info = self.env.step(act_env)
            next_obs = np.asarray(next_obs, dtype=np.float32).reshape(-1)

            rec = RunnerStepRecord(
                obs=cur_obs.copy(),
                act_flat=act_flat.copy(),
                rew=float(rew),
                next_obs=next_obs.copy(),
                done=bool(done),
                info=info,
            )
            steps.append(rec)
            total_reward += float(rew)

            if self.replay is not None and store_replay:
                self.replay.store_step(
                    obs=cur_obs,
                    act=act_flat,
                    rew=rew,
                    next_obs=next_obs,
                    done=done,
                )

            self.obs_history.append(next_obs)
            cur_obs = next_obs

            if done:
                break

        return ChunkExecutionResult(
            plan=plan,
            steps=steps,
            final_obs=cur_obs.copy(),
            total_reward=float(total_reward),
        )

    def rollout_one_chunk(
        self,
        obs: Optional[np.ndarray] = None,
        deterministic: bool = False,
        store_replay: bool = True,
        return_unit: bool = True,
    ) -> ChunkExecutionResult:
        """
        Generate one chunk and immediately execute its first K actions.
        """
        plan = self.plan_chunk(
            obs=obs,
            deterministic=deterministic,
            return_unit=return_unit,
        )
        return self.execute_chunk_plan(
            plan=plan,
            store_replay=store_replay,
        )

    # ============================================================
    # Multi-step rollout helpers
    # ============================================================
    def rollout_steps(
        self,
        num_steps: int,
        deterministic: bool = False,
        store_replay: bool = True,
        return_chunk_records: bool = False,
    ):
        """
        Roll out approximately num_steps environment steps.

        Since one chunk may execute multiple steps, the actual executed step count
        will stop once it reaches or exceeds num_steps.

        Returns
        -------
        final_obs, total_reward, step_records
        optionally:
            chunk_results
        """
        assert num_steps >= 1

        total_reward = 0.0
        step_records: List[RunnerStepRecord] = []
        chunk_results: List[ChunkExecutionResult] = []

        executed = 0
        while executed < num_steps:
            result = self.rollout_one_chunk(
                deterministic=deterministic,
                store_replay=store_replay,
                return_unit=False,
            )
            chunk_results.append(result)
            step_records.extend(result.steps)
            total_reward += result.total_reward
            executed += len(result.steps)

            if len(result.steps) == 0:
                break
            if result.steps[-1].done:
                break

        final_obs = self.obs_history.last()

        if return_chunk_records:
            return final_obs, float(total_reward), step_records, chunk_results
        return final_obs, float(total_reward), step_records

    # ============================================================
    # Utility
    # ============================================================
    def _flat_to_env_action(self, act_flat: np.ndarray) -> np.ndarray:
        """
        Convert flat action:
            (act_dim,)
        to env action:
            (n_uavs, 2)
        """
        act_flat = np.asarray(act_flat, dtype=np.float32).reshape(-1)
        assert act_flat.shape[0] == self.act_dim, (
            f"Flat action dim mismatch: {act_flat.shape[0]} vs {self.act_dim}"
        )
        return act_flat.reshape(self.n_uavs, 2).astype(np.float32)

    def current_obs(self) -> np.ndarray:
        return self.obs_history.last()

    def current_obs_history(self) -> np.ndarray:
        return self.obs_history.get()

    def get_exec_len(self) -> int:
        return int(self.exec_len)

    def get_chunk_len(self) -> int:
        return int(self.chunk_len)